version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build || echo "No build step"
      - run:
          name: Run SonarQube Scan
          command: |
            cd server
            sonar-scanner \
              -Dsonar.host.url=//https://sonarcloud.io \
              -Dsonar.projectKey=ST10215222_CustomerPortal_INSY7314 \
              -Dsonar.organization=ST10215222 \
              -Dsonar.sources=. \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
